name: Build with Bazel

on: [pull_request]

jobs:
  test:
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1

      - name: Use Xcode 11
        run: sudo xcode-select -s /Applications/Xcode_11.app

      - name: Install Bazel
        run: brew install bazel

      - name: Build with Bazel
        run: bazel build //MovieSwift:MovieSwift
