name: Build with Bazel

on: [pull_request]

jobs:
  test:
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1

      - name: Use Xcode 11
        run: sudo xcode-select -s /Applications/Xcode_11.app

      - name: Install Bazel
        run: brew install bazel

      - name: Download key
        run: echo $GCS_SERVICE_ACCOUNT_KEY | base64 -D > service-account-key.json
        env:
          GCS_SERVICE_ACCOUNT_KEY: ${{ secrets.GCS_SERVICE_ACCOUNT_KEY }}

      - name: Build with Bazel
        run: >
          bazel build //MovieSwift:MovieSwift
          --remote_http_cache=https://storage.googleapis.com/bazel-movieswiftui-sandbox
          --google_credentials=service-account-key.json
